=== mastersign/mediacategorizer-ui/Scaleton/Scaleton.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="Scaleton" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:simpleType name="KIND_OF_TYPE">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Class" />
      <xs:enumeration value="Struct" />
      <xs:enumeration value="Interface" />
      <xs:enumeration value="Enum" />
      <xs:enumeration value="Delegate" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="COLLECTION_TYPE">
    <xs:restriction base="xs:string">
      <xs:enumeration value="BindingList" />
      <xs:enumeration value="ObservableCollection" />
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="FEATURE_EQUATABLE">
    <xs:attribute name="overrideOperators" type="xs:boolean" default="false" use="optional" />
  </xs:complexType>

  <xs:simpleType name="FEATURE_CHANGE_TRACKING_LEVEL">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Notification" />
      <xs:enumeration value="Tracking" />
      <xs:enumeration value="Revertible" />
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="FEATURE_CHANGE_TRACKING">
    <xs:attribute name="level" type="FEATURE_CHANGE_TRACKING_LEVEL" default="Notification" use="optional" />
    <xs:attribute name="collectionType" type="COLLECTION_TYPE" default="ObservableCollection" use="optional" />
    <xs:attribute name="escalateChangeState" type="xs:boolean" default="false" use="optional" />
  </xs:complexType>

  <xs:complexType name="MODEL_FEATURES">
    <xs:all>
      <xs:element name="ToString" minOccurs="0" maxOccurs="1" />
      <xs:element name="Equatable" minOccurs="0" maxOccurs="1" type="FEATURE_EQUATABLE" />
      <xs:element name="Comparable" minOccurs="0" maxOccurs="1" />
      <xs:element name="ChangeTracking" minOccurs="0" maxOccurs="1" type="FEATURE_CHANGE_TRACKING" />
      <xs:element name="Cloneable" minOccurs="0" maxOccurs="1" />
    </xs:all>
  </xs:complexType>

  <xs:complexType name="DOCUMENTATION" mixed="true">
    <xs:sequence>
      <xs:any processContents="skip" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ENUM_MEMBER">
    <xs:sequence>
      <xs:element name="Doc" type="DOCUMENTATION" minOccurs="0" maxOccurs="1" />
    </xs:sequence>
    <xs:attribute name="name" type="xs:Name" use="required" />
  </xs:complexType>

  <xs:complexType name="CLASS_PROPERTY">
    <xs:sequence>
      <xs:element name="Doc" type="DOCUMENTATION" minOccurs="0" maxOccurs="1" />
      <xs:element name="DefaultValue" type="xs:string" minOccurs="0" maxOccurs="1" />
    </xs:sequence>
    <xs:attribute name="name" type="xs:Name" use="required" />
    <xs:attribute name="type" type="xs:string" default="string" use="optional" />
    <xs:attribute name="isCollection" type="xs:boolean" default="false" use="optional" />
    <xs:attribute name="defaultInitialization" type="xs:boolean" default="true" use="optional" />
  </xs:complexType>

  <xs:element name="Model">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Namespace" type="xs:string" minOccurs="1" maxOccurs="1" />
        <xs:element name="Dependencies" minOccurs="0" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Assembly" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="ReferencedTypes" minOccurs="0" maxOccurs="1">
          <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
              <xs:element name="ReferencedType">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Interface" minOccurs="0" maxOccurs="unbounded" type="xs:string" />
                  </xs:sequence>
                  <xs:attribute name="id" type="xs:Name" use="required" />
                  <xs:attribute name="name" type="xs:string" use="required" />
                  <xs:attribute name="kind" type="KIND_OF_TYPE" use="optional" default="Class" />
                </xs:complexType>
              </xs:element>
            </xs:choice>
          </xs:complexType>
        </xs:element>
        <xs:element name="ModelFeatures" type="MODEL_FEATURES" minOccurs="0" maxOccurs="1" />
        <xs:element name="Types" minOccurs="1" maxOccurs="1">
          <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
              <xs:element name="Class">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Doc" type="DOCUMENTATION" minOccurs="0" maxOccurs="1" />
                    <xs:element name="CustomInitializer" type="xs:Name" minOccurs="0" maxOccurs="1" />
                    <xs:choice minOccurs="0" maxOccurs="unbounded">
                      <xs:element name="Property" type="CLASS_PROPERTY" />
                    </xs:choice>
                    <xs:element name="EqualityMembers" minOccurs="0" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Property" type="xs:Name" minOccurs="1" maxOccurs="unbounded" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="name" type="xs:Name" use="required" />
                </xs:complexType>
              </xs:element>
              <xs:element name="Enum">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Doc" type="DOCUMENTATION" minOccurs="0" maxOccurs="1" />
                    <xs:element name="Member" type="ENUM_MEMBER" minOccurs="1" maxOccurs="unbounded" />
                  </xs:sequence>
                  <xs:attribute name="name" type="xs:Name" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:choice>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== mastersign/mediacategorizer-ui/model/Model.xml
<?xml version="1.0" encoding="utf-8" ?>
<Model xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns="http://scaleton.mastersign.de/2013/model"
       xsi:noNamespaceSchemaLocation="../Scaleton/Scaleton.xsd">
  
  <Namespace>de.fhb.oll.mediacategorizer.model</Namespace>
  
  <ReferencedTypes></ReferencedTypes>
  
  <ModelFeatures>
    <ToString />
    <Equatable />
    <ChangeTracking level="Tracking" escalateChangeState="true" propagateTransaction="true" />
  </ModelFeatures>
  
  <Types>
    <Class name="Project">
      <CustomInitializer>Initialize</CustomInitializer>
      <Property name="Name">
        <DefaultValue>No Name</DefaultValue>
      </Property>
      <Property name="Description">
        <DefaultValue>No Description</DefaultValue>
      </Property>
      
      <Property name="OutputDir" type="string">
        <DefaultValue>output</DefaultValue>
      </Property>

      <Property name="Configuration" type="Configuration" />
      <Property name="Categories" type="Category" isCollection="true" />
      <Property name="Media" type="Media" isCollection="true" />
    </Class>
    
    <Class name="Configuration">
      <Property name="MinConfidence" type="float">
        <DefaultValue>0.4</DefaultValue>
      </Property>
      <Property name="GoodConfidence" type="float">
        <DefaultValue>0.7</DefaultValue>
      </Property>
      <Property name="MinRelativeAppearance" type="float">
        <DefaultValue>0.25</DefaultValue>
      </Property>
      <Property name="MinMatchScore" type="float">
        <DefaultValue>0.0</DefaultValue>
      </Property>

      <Property name="IndexFilter" type="FilterParameter" />

      <Property name="MainCloud" type="CloudParameter" />
      <Property name="MediaCloud" type="CloudParameter" />
      <Property name="CategoryCloud" type="CloudParameter" />

      <Property name="ParallelProc" type="bool">
        <DefaultValue>true</DefaultValue>
      </Property>
      <Property name="SkipWordClouds" type="bool">
        <DefaultValue>false</DefaultValue>
      </Property>
      <Property name="SkipWordIncludes" type="bool">
        <DefaultValue>false</DefaultValue>
      </Property>
      <Property name="SkipMatchIncludes" type="bool">
        <DefaultValue>false</DefaultValue>
      </Property>
      <Property name="SkipMediaCopy" type="bool">
        <DefaultValue>false</DefaultValue>
      </Property>
    </Class>

    <Class name="FilterParameter">
      <Property name="BlacklistResource" type="string">
        <DefaultValue>top10000de.txt</DefaultValue>
      </Property>
      <Property name="BlacklistMaxSize" type="int">
        <DefaultValue>2000</DefaultValue>
      </Property>
      
      <Property name="FilterNotShort" type="bool">
        <DefaultValue>true</DefaultValue>
      </Property>
      <Property name="FilterNoun" type="bool">
        <DefaultValue>true</DefaultValue>
      </Property>
      <Property name="FilterMinConfidence" type="bool">
        <DefaultValue>true</DefaultValue>
      </Property>
      <Property name="FilterGoodConfidence" type="bool">
        <DefaultValue>false</DefaultValue>
      </Property>
      <Property name="FilterNoPunctuation" type="bool">
        <DefaultValue>true</DefaultValue>
      </Property>
      <Property name="FilterNotInBlacklist" type="bool">
        <DefaultValue>true</DefaultValue>
      </Property>
    </Class>

    <Enum name="CloudPrecision">
      <Member name="Low" />
      <Member name="Medium" />
      <Member name="High" />
    </Enum>

    <Class name="ColorRGBA">
      <Property name="R" type="float">
        <DefaultValue>0.0</DefaultValue>
      </Property>
      <Property name="G" type="float">
        <DefaultValue>0.5</DefaultValue>
      </Property>
      <Property name="B" type="float">
        <DefaultValue>1.0</DefaultValue>
      </Property>
      <Property name="A" type="float">
        <DefaultValue>1.0</DefaultValue>
      </Property>
    </Class>

    <Class name="CloudParameter">
      <CustomInitializer>Initialize</CustomInitializer>
      
      <Property name="Width" type="int">
        <DefaultValue>640</DefaultValue>
      </Property>
      <Property name="Height" type="int">
        <DefaultValue>480</DefaultValue>
      </Property>
      
      <Property name="Precision" type="CloudPrecision">
        <DefaultValue>Medium</DefaultValue>
      </Property>
      <Property name="OrderPriority" type="float">
        <DefaultValue>0.6</DefaultValue>
      </Property>
      
      <Property name="FontFamily" type="string">
        <DefaultValue>Arial</DefaultValue>
      </Property>
      <Property name="FontBold" type="bool">
        <DefaultValue>true</DefaultValue>
      </Property>
      <Property name="FontItalic" type="bool">
        <DefaultValue>false</DefaultValue>
      </Property>
      <Property name="MinFontSize" type="float">
        <DefaultValue>13.0</DefaultValue>
      </Property>
      <Property name="MaxFontSize" type="float">
        <DefaultValue>80.0</DefaultValue>
      </Property>

      <Property name="Color" type="ColorRGBA" />
      <Property name="BackgroundColor" type="ColorRGBA" />
    </Class>
    
    <Enum name="CategoryResourceType">
      <Member name="Plain" />
      <Member name="Html" />
      <Member name="Wikipedia" />
    </Enum>

    <Class name="CategoryResource">
      <Property name="Type" type="CategoryResourceType">
        <DefaultValue>Plain</DefaultValue>
      </Property>
      <Property name="Url" type="string">
        <DefaultValue>null</DefaultValue>
      </Property>
    </Class>

    <Class name="Category">
      <Property name="Id">
        <DefaultValue>_empty_</DefaultValue>
      </Property>
      <Property name="Name">
        <DefaultValue>No Name</DefaultValue>
      </Property>
      
      <Property name="Resources" type="CategoryResource" isCollection="true" />
    </Class>

    <Class name="Media">
      <Property name="Id" />
      <Property name="Name" />
      <Property name="MediaFile" />
      <Property name="AudioFile" />
      <Property name="ResultsFile" />
      <Property name="WaveformFile" />
      <EqualityMembers>
        <Property>Id</Property>
      </EqualityMembers>
    </Class>
  </Types>
</Model>
